af = "MMM y"
af-NA = "MMM y"
af-ZA = "MMM y"
agq = "MMM y"
agq-CM = "MMM y"
ak = "MMM y"
ak-GH = "MMM y"
am = "MMM y"
am-ET = "MMM y"
ar = "MMM y"
ar-001 = "MMM y"
ar-AE = "MMM y"
ar-BH = "MMM y"
ar-DJ = "MMM y"
ar-DZ = "MMM y"
ar-EG = "MMM y"
ar-EH = "MMM y"
ar-ER = "MMM y"
ar-IL = "MMM y"
ar-IQ = "MMM y"
ar-JO = "MMM y"
ar-KM = "MMM y"
ar-KW = "MMM y"
ar-LB = "MMM y"
ar-LY = "MMM y"
ar-MA = "MMM y"
ar-MR = "MMM y"
ar-OM = "MMM y"
ar-PS = "MMM y"
ar-QA = "MMM y"
ar-SA = "MMM y G"
ar-SD = "MMM y"
ar-SO = "MMM y"
ar-SS = "MMM y"
ar-SY = "MMM y"
ar-TD = "MMM y"
ar-TN = "MMM y"
ar-YE = "MMM y"
as = "MMM y"
as-IN = "MMM y"
asa = "MMM y"
asa-TZ = "MMM y"
ast = "MMM y"
ast-ES = "MMM y"
az = "MMM y"
az-Cyrl = "MMM, y"
az-Cyrl-AZ = "MMM, y"
az-Latn = "MMM y"
az-Latn-AZ = "MMM y"
bas = "MMM y"
bas-CM = "MMM y"
be = "LLL y"
be-BY = "LLL y"
bem = "MMM y"
bem-ZM = "MMM y"
bez = "MMM y"
bez-TZ = "MMM y"
bg = "MM.y 'г'."
bg-BG = "MM.y 'г'."
bm = "MMM y"
bm-ML = "MMM y"
bn = "MMM y"
bn-BD = "MMM y"
bn-IN = "MMM y"
bo = "y LLL"
bo-CN = "y LLL"
bo-IN = "y LLL"
br = "MMM y"
br-FR = "MMM y"
brx = "MMM y"
brx-IN = "MMM y"
bs = "MMM y."
bs-Cyrl = "MMM y."
bs-Cyrl-BA = "MMM y."
bs-Latn = "MMM y."
bs-Latn-BA = "MMM y."
ca = "LLL 'de' y"
ca-AD = "LLL 'de' y"
ca-ES = "LLL 'de' y"
ca-FR = "LLL 'de' y"
ca-IT = "LLL 'de' y"
ccp = "MMM y"
ccp-BD = "MMM y"
ccp-IN = "MMM y"
ce = "y MMM"
ce-RU = "y MMM"
ceb = "MMM y"
ceb-PH = "MMM y"
cgg = "MMM y"
cgg-UG = "MMM y"
chr = "MMM y"
chr-US = "MMM y"
ckb = "MMMی y"
ckb-IQ = "MMMی y"
ckb-IR = "MMMی y"
cs = "LLLL y"
cs-CZ = "LLLL y"
cy = "MMM y"
cy-GB = "MMM y"
da = "MMM y"
da-DK = "MMM y"
da-GL = "MMM y"
dav = "MMM y"
dav-KE = "MMM y"
de = "MMM y"
de-AT = "MMM y"
de-BE = "MMM y"
de-CH = "MMM y"
de-DE = "MMM y"
de-IT = "MMM y"
de-LI = "MMM y"
de-LU = "MMM y"
dje = "MMM y"
dje-NE = "MMM y"
doi = "MMM y"
doi-IN = "MMM y"
dsb = "MMM y"
dsb-DE = "MMM y"
dua = "MMM y"
dua-CM = "MMM y"
dyo = "MMM y"
dyo-SN = "MMM y"
dz = "y སྤྱི་ཟླ་MMM"
dz-BT = "y སྤྱི་ཟླ་MMM"
ebu = "MMM y"
ebu-KE = "MMM y"
ee = "MMM y"
ee-GH = "MMM y"
ee-TG = "MMM y"
el = "MMM y"
el-CY = "MMM y"
el-GR = "MMM y"
en = "MMM y"
en-001 = "MMM y"
en-150 = "MMM y"
en-AE = "MMM y"
en-AG = "MMM y"
en-AI = "MMM y"
en-AS = "MMM y"
en-AT = "MMM y"
en-AU = "MMM y"
en-BB = "MMM y"
en-BE = "MMM y"
en-BI = "MMM y"
en-BM = "MMM y"
en-BS = "MMM y"
en-BW = "MMM y"
en-BZ = "MMM y"
en-CA = "MMM y"
en-CC = "MMM y"
en-CH = "MMM y"
en-CK = "MMM y"
en-CM = "MMM y"
en-CX = "MMM y"
en-CY = "MMM y"
en-DE = "MMM y"
en-DG = "MMM y"
en-DK = "MMM y"
en-DM = "MMM y"
en-ER = "MMM y"
en-FI = "MMM y"
en-FJ = "MMM y"
en-FK = "MMM y"
en-FM = "MMM y"
en-GB = "MMM y"
en-GD = "MMM y"
en-GG = "MMM y"
en-GH = "MMM y"
en-GI = "MMM y"
en-GM = "MMM y"
en-GU = "MMM y"
en-GY = "MMM y"
en-HK = "MMM y"
en-IE = "MMM y"
en-IL = "MMM y"
en-IM = "MMM y"
en-IN = "MMM y"
en-IO = "MMM y"
en-JE = "MMM y"
en-JM = "MMM y"
en-KE = "MMM y"
en-KI = "MMM y"
en-KN = "MMM y"
en-KY = "MMM y"
en-LC = "MMM y"
en-LR = "MMM y"
en-LS = "MMM y"
en-MG = "MMM y"
en-MH = "MMM y"
en-MO = "MMM y"
en-MP = "MMM y"
en-MS = "MMM y"
en-MT = "MMM y"
en-MU = "MMM y"
en-MV = "MMM y"
en-MW = "MMM y"
en-MY = "MMM y"
en-NA = "MMM y"
en-NF = "MMM y"
en-NG = "MMM y"
en-NL = "MMM y"
en-NR = "MMM y"
en-NU = "MMM y"
en-NZ = "MMM y"
en-PG = "MMM y"
en-PH = "MMM y"
en-PK = "MMM y"
en-PN = "MMM y"
en-PR = "MMM y"
en-PW = "MMM y"
en-RW = "MMM y"
en-SB = "MMM y"
en-SC = "MMM y"
en-SD = "MMM y"
en-SE = "MMM y"
en-SG = "MMM y"
en-SH = "MMM y"
en-SI = "MMM y"
en-SL = "MMM y"
en-SS = "MMM y"
en-SX = "MMM y"
en-SZ = "MMM y"
en-TC = "MMM y"
en-TK = "MMM y"
en-TO = "MMM y"
en-TT = "MMM y"
en-TV = "MMM y"
en-TZ = "MMM y"
en-UG = "MMM y"
en-UM = "MMM y"
en-US = "MMM y"
en-US-POSIX = "MMM y"
en-VC = "MMM y"
en-VG = "MMM y"
en-VI = "MMM y"
en-VU = "MMM y"
en-WS = "MMM y"
en-ZA = "MMM y"
en-ZM = "MMM y"
en-ZW = "MMM y"
eo = "y MMM"
eo-001 = "y MMM"
es = "MMM y"
es-419 = "MMM y"
es-AR = "MMM y"
es-BO = "MMM y"
es-BR = "MMM y"
es-BZ = "MMM y"
es-CL = "MMM y"
es-CO = "MMM 'de' y"
es-CR = "MMM y"
es-CU = "MMM y"
es-DO = "MMM y"
es-EA = "MMM y"
es-EC = "MMM y"
es-ES = "MMM y"
es-GQ = "MMM y"
es-GT = "MMM y"
es-HN = "MMM y"
es-IC = "MMM y"
es-MX = "MMM y"
es-NI = "MMM y"
es-PA = "MMM y"
es-PE = "MMM y"
es-PH = "MMM y"
es-PR = "MMM y"
es-PY = "MMM y"
es-SV = "MMM y"
es-US = "MMM y"
es-UY = "MMM y"
es-VE = "MMM y"
et = "MMM y"
et-EE = "MMM y"
eu = "y MMM"
eu-ES = "y MMM"
ewo = "MMM y"
ewo-CM = "MMM y"
fa = "MMM y"
fa-AF = "MMM y"
fa-IR = "MMM y"
ff = "MMM y"
ff-Adlm = "MMM y"
ff-Adlm-BF = "MMM y"
ff-Adlm-CM = "MMM y"
ff-Adlm-GH = "MMM y"
ff-Adlm-GM = "MMM y"
ff-Adlm-GN = "MMM y"
ff-Adlm-GW = "MMM y"
ff-Adlm-LR = "MMM y"
ff-Adlm-MR = "MMM y"
ff-Adlm-NE = "MMM y"
ff-Adlm-NG = "MMM y"
ff-Adlm-SL = "MMM y"
ff-Adlm-SN = "MMM y"
ff-Latn = "MMM y"
ff-Latn-BF = "MMM y"
ff-Latn-CM = "MMM y"
ff-Latn-GH = "MMM y"
ff-Latn-GM = "MMM y"
ff-Latn-GN = "MMM y"
ff-Latn-GW = "MMM y"
ff-Latn-LR = "MMM y"
ff-Latn-MR = "MMM y"
ff-Latn-NE = "MMM y"
ff-Latn-NG = "MMM y"
ff-Latn-SL = "MMM y"
ff-Latn-SN = "MMM y"
fi = "LLL y"
fi-FI = "LLL y"
fil = "MMM y"
fil-PH = "MMM y"
fo = "MMM y"
fo-DK = "MMM y"
fo-FO = "MMM y"
fr = "MMM y"
fr-BE = "MMM y"
fr-BF = "MMM y"
fr-BI = "MMM y"
fr-BJ = "MMM y"
fr-BL = "MMM y"
fr-CA = "MMM y"
fr-CD = "MMM y"
fr-CF = "MMM y"
fr-CG = "MMM y"
fr-CH = "MMM y"
fr-CI = "MMM y"
fr-CM = "MMM y"
fr-DJ = "MMM y"
fr-DZ = "MMM y"
fr-FR = "MMM y"
fr-GA = "MMM y"
fr-GF = "MMM y"
fr-GN = "MMM y"
fr-GP = "MMM y"
fr-GQ = "MMM y"
fr-HT = "MMM y"
fr-KM = "MMM y"
fr-LU = "MMM y"
fr-MA = "MMM y"
fr-MC = "MMM y"
fr-MF = "MMM y"
fr-MG = "MMM y"
fr-ML = "MMM y"
fr-MQ = "MMM y"
fr-MR = "MMM y"
fr-MU = "MMM y"
fr-NC = "MMM y"
fr-NE = "MMM y"
fr-PF = "MMM y"
fr-PM = "MMM y"
fr-RE = "MMM y"
fr-RW = "MMM y"
fr-SC = "MMM y"
fr-SN = "MMM y"
fr-SY = "MMM y"
fr-TD = "MMM y"
fr-TG = "MMM y"
fr-TN = "MMM y"
fr-VU = "MMM y"
fr-WF = "MMM y"
fr-YT = "MMM y"
fur = "MMM y"
fur-IT = "MMM y"
fy = "MMM y"
fy-NL = "MMM y"
ga = "MMM y"
ga-GB = "MMM y"
ga-IE = "MMM y"
gd = "LLL Y"
gd-GB = "LLL Y"
gl = "MMM 'de' y"
gl-ES = "MMM 'de' y"
gsw = "MMM y"
gsw-CH = "MMM y"
gsw-FR = "MMM y"
gsw-LI = "MMM y"
gu = "MMM y"
gu-IN = "MMM y"
guz = "MMM y"
guz-KE = "MMM y"
gv = "y MMM"
gv-IM = "y MMM"
ha = "MMM y"
ha-GH = "MMM y"
ha-NE = "MMM y"
ha-NG = "MMM y"
haw = "MMM y"
haw-US = "MMM y"
he = "MMM y"
he-IL = "MMM y"
hi = "MMM y"
hi-IN = "MMM y"
hi-Latn = "MMM y"
hi-Latn-IN = "MMM y"
hr = "LLL y."
hr-BA = "LLL y."
hr-HR = "LLL y."
hsb = "MMM y"
hsb-DE = "MMM y"
hu = "y. MMM"
hu-HU = "y. MMM"
hy = "y թ. LLL"
hy-AM = "y թ. LLL"
ia = "MMM y"
ia-001 = "MMM y"
id = "MMM y"
id-ID = "MMM y"
ig = "MMM y"
ig-NG = "MMM y"
ii = "y MMM"
ii-CN = "y MMM"
is = "MMM y"
is-IS = "MMM y"
it = "MMM y"
it-CH = "MMM y"
it-IT = "MMM y"
it-SM = "MMM y"
it-VA = "MMM y"
ja = "y年M月"
ja-JP = "y年M月"
jgo = "y MMM"
jgo-CM = "y MMM"
jmc = "MMM y"
jmc-TZ = "MMM y"
jv = "MMM y"
jv-ID = "MMM y"
ka = "MMM. y"
ka-GE = "MMM. y"
kab = "MMM y"
kab-DZ = "MMM y"
kam = "MMM y"
kam-KE = "MMM y"
kde = "MMM y"
kde-TZ = "MMM y"
kea = "LLL y"
kea-CV = "LLL y"
kgp = "MMM, y"
kgp-BR = "MMM, y"
khq = "MMM y"
khq-ML = "MMM y"
ki = "MMM y"
ki-KE = "MMM y"
kk = "y 'ж'. MMM"
kk-KZ = "y 'ж'. MMM"
kkj = "MMM y"
kkj-CM = "MMM y"
kl = "y MMM"
kl-GL = "y MMM"
kln = "MMM y"
kln-KE = "MMM y"
km = "MMM y"
km-KH = "MMM y"
kn = "MMM y"
kn-IN = "MMM y"
ko = "y년 MMM"
ko-KP = "y년 MMM"
ko-KR = "y년 MMM"
kok = "y MMM"
kok-IN = "y MMM"
ks = "MMM y"
ks-Arab = "MMM y"
ks-Arab-IN = "MMM y"
ks-Deva = "y MMM"
ks-Deva-IN = "y MMM"
ksb = "MMM y"
ksb-TZ = "MMM y"
ksf = "MMM y"
ksf-CM = "MMM y"
ksh = "MMM y"
ksh-DE = "MMM y"
ku = "y MMM"
ku-TR = "y MMM"
kw = "y MMM"
kw-GB = "y MMM"
ky = "y-'ж'. MMM"
ky-KG = "y-'ж'. MMM"
lag = "MMM y"
lag-TZ = "MMM y"
lb = "MMM y"
lb-LU = "MMM y"
lg = "MMM y"
lg-UG = "MMM y"
lkt = "y MMM"
lkt-US = "y MMM"
ln = "MMM y"
ln-AO = "MMM y"
ln-CD = "MMM y"
ln-CF = "MMM y"
ln-CG = "MMM y"
lo = "MMM y"
lo-LA = "MMM y"
lrc = "G y MMM"
lrc-IQ = "y MMM"
lrc-IR = "G y MMM"
lt = "y-MM"
lt-LT = "y-MM"
lu = "MMM y"
lu-CD = "MMM y"
luo = "MMM y"
luo-KE = "MMM y"
luy = "MMM y"
luy-KE = "MMM y"
lv = "y. 'g'. MMM"
lv-LV = "y. 'g'. MMM"
mai = "MMM y"
mai-IN = "MMM y"
mas = "MMM y"
mas-KE = "MMM y"
mas-TZ = "MMM y"
mer = "MMM y"
mer-KE = "MMM y"
mfe = "MMM y"
mfe-MU = "MMM y"
mg = "MMM y"
mg-MG = "MMM y"
mgh = "MMM y"
mgh-MZ = "MMM y"
mgo = "y MMM"
mgo-CM = "y MMM"
mi = "MMM y"
mi-NZ = "MMM y"
mk = "MMM y 'г'."
mk-MK = "MMM y 'г'."
ml = "y MMM"
ml-IN = "y MMM"
mn = "y 'оны' MMM"
mn-MN = "y 'оны' MMM"
mni = "MMM y"
mni-Beng = "MMM y"
mni-Beng-IN = "MMM y"
mr = "MMM y"
mr-IN = "MMM y"
ms = "MMM y"
ms-BN = "MMM y"
ms-ID = "MMM y"
ms-MY = "MMM y"
ms-SG = "MMM y"
mt = "MMM y"
mt-MT = "MMM y"
mua = "MMM y"
mua-CM = "MMM y"
my = "MMM y"
my-MM = "MMM y"
mzn = "G y MMM"
mzn-IR = "G y MMM"
naq = "MMM y"
naq-NA = "MMM y"
nb = "MMM y"
nb-NO = "MMM y"
nb-SJ = "MMM y"
nd = "MMM y"
nd-ZW = "MMM y"
ne = "y MMM"
ne-IN = "y MMM"
ne-NP = "y MMM"
nl = "MMM y"
nl-AW = "MMM y"
nl-BE = "MMM y"
nl-BQ = "MMM y"
nl-CW = "MMM y"
nl-NL = "MMM y"
nl-SR = "MMM y"
nl-SX = "MMM y"
nmg = "MMM y"
nmg-CM = "MMM y"
nn = "MMM y"
nn-NO = "MMM y"
nnh = "MMM y"
nnh-CM = "MMM y"
; The following line has a space before the key because it is a keyword
 no = "MMM y"
nus = "MMM y"
nus-SS = "MMM y"
nyn = "MMM y"
nyn-UG = "MMM y"
om = "y MMM"
om-ET = "y MMM"
om-KE = "y MMM"
or = "MMM y"
or-IN = "MMM y"
os = "LLL y"
os-GE = "LLL y"
os-RU = "LLL y"
pa = "MMM y"
pa-Arab = "MMM y"
pa-Arab-PK = "MMM y"
pa-Guru = "MMM y"
pa-Guru-IN = "MMM y"
pcm = "MMM y"
pcm-NG = "MMM y"
pl = "LLL y"
pl-PL = "LLL y"
ps = "د G y د MMM"
ps-AF = "د G y د MMM"
ps-PK = "د G y د MMM"
pt = "MMM 'de' y"
pt-AO = "MM/y"
pt-BR = "MMM 'de' y"
pt-CH = "MM/y"
pt-CV = "MM/y"
pt-GQ = "MM/y"
pt-GW = "MM/y"
pt-LU = "MM/y"
pt-MO = "MM/y"
pt-MZ = "MM/y"
pt-PT = "MM/y"
pt-ST = "MM/y"
pt-TL = "MM/y"
qu = "MMM y"
qu-BO = "MMM y"
qu-EC = "MMM y"
qu-PE = "MMM y"
rm = "LLL y"
rm-CH = "LLL y"
rn = "MMM y"
rn-BI = "MMM y"
ro = "MMM y"
ro-MD = "MMM y"
ro-RO = "MMM y"
rof = "MMM y"
rof-TZ = "MMM y"
ru = "LLL y 'г'."
ru-BY = "LLL y 'г'."
ru-KG = "LLL y 'г'."
ru-KZ = "LLL y 'г'."
ru-MD = "LLL y 'г'."
ru-RU = "LLL y 'г'."
ru-UA = "LLL y 'г'."
rw = "y MMM"
rw-RW = "y MMM"
rwk = "MMM y"
rwk-TZ = "MMM y"
sa = "MMM y"
sa-IN = "MMM y"
sah = "y MMM"
sah-RU = "y MMM"
saq = "MMM y"
saq-KE = "MMM y"
sat = "y MMM"
sat-Olck = "y MMM"
sat-Olck-IN = "y MMM"
sbp = "MMM y"
sbp-TZ = "MMM y"
sc = "MMM y"
sc-IT = "MMM y"
sd = "y MMM"
sd-Arab = "y MMM"
sd-Arab-PK = "y MMM"
sd-Deva = "MMM y"
sd-Deva-IN = "MMM y"
se = "y MMM"
se-FI = "MMM y"
se-NO = "y MMM"
se-SE = "y MMM"
seh = "MMM 'de' y"
seh-MZ = "MMM 'de' y"
ses = "MMM y"
ses-ML = "MMM y"
sg = "MMM y"
sg-CF = "MMM y"
shi = "MMM y"
shi-Latn = "MMM y"
shi-Latn-MA = "MMM y"
shi-Tfng = "MMM y"
shi-Tfng-MA = "MMM y"
si = "y MMM"
si-LK = "y MMM"
sk = "M/y"
sk-SK = "M/y"
sl = "MMM y"
sl-SI = "MMM y"
smn = "LLL y"
smn-FI = "LLL y"
sn = "y MMM"
sn-ZW = "y MMM"
so = "MMM y"
so-DJ = "MMM y"
so-ET = "MMM y"
so-KE = "MMM y"
so-SO = "MMM y"
sq = "MMM y"
sq-AL = "MMM y"
sq-MK = "MMM y"
sq-XK = "MMM y"
sr = "MMM y."
sr-Cyrl = "MMM y."
sr-Cyrl-BA = "MMM y."
sr-Cyrl-ME = "MMM y."
sr-Cyrl-RS = "MMM y."
sr-Cyrl-XK = "MMM y."
sr-Latn = "MMM y."
sr-Latn-BA = "MMM y."
sr-Latn-ME = "MMM y."
sr-Latn-RS = "MMM y."
sr-Latn-XK = "MMM y."
su = "MMM y"
su-Latn = "MMM y"
su-Latn-ID = "MMM y"
sv = "MMM y"
sv-AX = "MMM y"
sv-FI = "MMM y"
sv-SE = "MMM y"
sw = "MMM y"
sw-CD = "MMM y"
sw-KE = "MMM y"
sw-TZ = "MMM y"
sw-UG = "MMM y"
ta = "MMM y"
ta-IN = "MMM y"
ta-LK = "MMM y"
ta-MY = "MMM y"
ta-SG = "MMM y"
te = "MMM y"
te-IN = "MMM y"
teo = "MMM y"
teo-KE = "MMM y"
teo-UG = "MMM y"
tg = "MMM y"
tg-TJ = "MMM y"
th = "MMM y"
th-TH = "MMM y"
ti = "MMM y"
ti-ER = "MMM y"
ti-ET = "MMM y"
tk = "MMM y"
tk-TM = "MMM y"
to = "MMM y"
to-TO = "MMM y"
tr = "MMM y"
tr-CY = "MMM y"
tr-TR = "MMM y"
tt = "y 'ел', MMM"
tt-RU = "y 'ел', MMM"
twq = "MMM y"
twq-NE = "MMM y"
tzm = "MMM y"
tzm-MA = "MMM y"
ug = "y MMM"
ug-CN = "y MMM"
uk = "LLL y 'р'."
uk-UA = "LLL y 'р'."
ur = "MMM y"
ur-IN = "MMM y"
ur-PK = "MMM y"
uz = "MMM, y"
uz-Arab = "G y MMM"
uz-Arab-AF = "G y MMM"
uz-Cyrl = "MMM, y"
uz-Cyrl-UZ = "MMM, y"
uz-Latn = "MMM, y"
uz-Latn-UZ = "MMM, y"
vai = "MMM y"
vai-Latn = "MMM y"
vai-Latn-LR = "MMM y"
vai-Vaii = "MMM y"
vai-Vaii-LR = "MMM y"
vi = "MMM y"
vi-VN = "MMM y"
vun = "MMM y"
vun-TZ = "MMM y"
wae = "MMM y"
wae-CH = "MMM y"
wo = "MMM y"
wo-SN = "MMM y"
xh = "y MMM"
xh-ZA = "y MMM"
xog = "MMM y"
xog-UG = "MMM y"
yav = "MMM y"
yav-CM = "MMM y"
yi = "MMM y"
yi-001 = "MMM y"
yo = "MMM y"
yo-BJ = "MMM y"
yo-NG = "MMM y"
yrl = "MMM y"
yrl-BR = "MMM y"
yrl-CO = "MMM y"
yrl-VE = "MMM y"
yue = "y年M月"
yue-Hans = "y年M月"
yue-Hans-CN = "y年M月"
yue-Hant = "y年M月"
yue-Hant-HK = "y年M月"
zgh = "MMM y"
zgh-MA = "MMM y"
zh = "y年M月"
zh-Hans = "y年M月"
zh-Hans-CN = "y年M月"
zh-CN = "y年M月"
zh-Hans-HK = "y年M月"
zh-Hans-MO = "y年M月"
zh-Hans-SG = "y年M月"
zh-Hant = "y年M月"
zh-Hant-HK = "y年M月"
zh-Hant-MO = "y年M月"
zh-Hant-TW = "y年M月"
zh-TW = "y年M月"
zu = "MMM y"
zu-ZA = "MMM y"
