af = "y"
af-NA = "y"
af-ZA = "y"
agq = "y"
agq-CM = "y"
ak = "y"
ak-GH = "y"
am = "y"
am-ET = "y"
ar = "y"
ar-001 = "y"
ar-AE = "y"
ar-BH = "y"
ar-DJ = "y"
ar-DZ = "y"
ar-EG = "y"
ar-EH = "y"
ar-ER = "y"
ar-IL = "y"
ar-IQ = "y"
ar-JO = "y"
ar-KM = "y"
ar-KW = "y"
ar-LB = "y"
ar-LY = "y"
ar-MA = "y"
ar-MR = "y"
ar-OM = "y"
ar-PS = "y"
ar-QA = "y"
ar-SA = "y G"
ar-SD = "y"
ar-SO = "y"
ar-SS = "y"
ar-SY = "y"
ar-TD = "y"
ar-TN = "y"
ar-YE = "y"
as = "y"
as-IN = "y"
asa = "y"
asa-TZ = "y"
ast = "y"
ast-ES = "y"
az = "y"
az-Cyrl = "y"
az-Cyrl-AZ = "y"
az-Latn = "y"
az-Latn-AZ = "y"
bas = "y"
bas-CM = "y"
be = "y"
be-BY = "y"
bem = "y"
bem-ZM = "y"
bez = "y"
bez-TZ = "y"
bg = "y 'г'."
bg-BG = "y 'г'."
bm = "y"
bm-ML = "y"
bn = "y"
bn-BD = "y"
bn-IN = "y"
bo = "y"
bo-CN = "y"
bo-IN = "y"
br = "y"
br-FR = "y"
brx = "y"
brx-IN = "y"
bs = "y."
bs-Cyrl = "y."
bs-Cyrl-BA = "y."
bs-Latn = "y."
bs-Latn-BA = "y."
ca = "y"
ca-AD = "y"
ca-ES = "y"
ca-FR = "y"
ca-IT = "y"
ccp = "y"
ccp-BD = "y"
ccp-IN = "y"
ce = "y"
ce-RU = "y"
ceb = "y"
ceb-PH = "y"
cgg = "y"
cgg-UG = "y"
chr = "y"
chr-US = "y"
ckb = "y"
ckb-IQ = "y"
ckb-IR = "G y"
cs = "y"
cs-CZ = "y"
cy = "y"
cy-GB = "y"
da = "y"
da-DK = "y"
da-GL = "y"
dav = "y"
dav-KE = "y"
de = "y"
de-AT = "y"
de-BE = "y"
de-CH = "y"
de-DE = "y"
de-IT = "y"
de-LI = "y"
de-LU = "y"
dje = "y"
dje-NE = "y"
doi = "y"
doi-IN = "y"
dsb = "y"
dsb-DE = "y"
dua = "y"
dua-CM = "y"
dyo = "y"
dyo-SN = "y"
dz = "y"
dz-BT = "y"
ebu = "y"
ebu-KE = "y"
ee = "y"
ee-GH = "y"
ee-TG = "y"
el = "y"
el-CY = "y"
el-GR = "y"
en = "y"
en-001 = "y"
en-150 = "y"
en-AE = "y"
en-AG = "y"
en-AI = "y"
en-AS = "y"
en-AT = "y"
en-AU = "y"
en-BB = "y"
en-BE = "y"
en-BI = "y"
en-BM = "y"
en-BS = "y"
en-BW = "y"
en-BZ = "y"
en-CA = "y"
en-CC = "y"
en-CH = "y"
en-CK = "y"
en-CM = "y"
en-CX = "y"
en-CY = "y"
en-DE = "y"
en-DG = "y"
en-DK = "y"
en-DM = "y"
en-ER = "y"
en-FI = "y"
en-FJ = "y"
en-FK = "y"
en-FM = "y"
en-GB = "y"
en-GD = "y"
en-GG = "y"
en-GH = "y"
en-GI = "y"
en-GM = "y"
en-GU = "y"
en-GY = "y"
en-HK = "y"
en-IE = "y"
en-IL = "y"
en-IM = "y"
en-IN = "y"
en-IO = "y"
en-JE = "y"
en-JM = "y"
en-KE = "y"
en-KI = "y"
en-KN = "y"
en-KY = "y"
en-LC = "y"
en-LR = "y"
en-LS = "y"
en-MG = "y"
en-MH = "y"
en-MO = "y"
en-MP = "y"
en-MS = "y"
en-MT = "y"
en-MU = "y"
en-MV = "y"
en-MW = "y"
en-MY = "y"
en-NA = "y"
en-NF = "y"
en-NG = "y"
en-NL = "y"
en-NR = "y"
en-NU = "y"
en-NZ = "y"
en-PG = "y"
en-PH = "y"
en-PK = "y"
en-PN = "y"
en-PR = "y"
en-PW = "y"
en-RW = "y"
en-SB = "y"
en-SC = "y"
en-SD = "y"
en-SE = "y"
en-SG = "y"
en-SH = "y"
en-SI = "y"
en-SL = "y"
en-SS = "y"
en-SX = "y"
en-SZ = "y"
en-TC = "y"
en-TK = "y"
en-TO = "y"
en-TT = "y"
en-TV = "y"
en-TZ = "y"
en-UG = "y"
en-UM = "y"
en-US = "y"
en-US-POSIX = "y"
en-VC = "y"
en-VG = "y"
en-VI = "y"
en-VU = "y"
en-WS = "y"
en-ZA = "y"
en-ZM = "y"
en-ZW = "y"
eo = "y"
eo-001 = "y"
es = "y"
es-419 = "y"
es-AR = "y"
es-BO = "y"
es-BR = "y"
es-BZ = "y"
es-CL = "y"
es-CO = "y"
es-CR = "y"
es-CU = "y"
es-DO = "y"
es-EA = "y"
es-EC = "y"
es-ES = "y"
es-GQ = "y"
es-GT = "y"
es-HN = "y"
es-IC = "y"
es-MX = "y"
es-NI = "y"
es-PA = "y"
es-PE = "y"
es-PH = "y"
es-PR = "y"
es-PY = "y"
es-SV = "y"
es-US = "y"
es-UY = "y"
es-VE = "y"
et = "y"
et-EE = "y"
eu = "y"
eu-ES = "y"
ewo = "y"
ewo-CM = "y"
fa = "y"
fa-AF = "y"
fa-IR = "y"
ff = "y"
ff-Adlm = "y"
ff-Adlm-BF = "y"
ff-Adlm-CM = "y"
ff-Adlm-GH = "y"
ff-Adlm-GM = "y"
ff-Adlm-GN = "y"
ff-Adlm-GW = "y"
ff-Adlm-LR = "y"
ff-Adlm-MR = "y"
ff-Adlm-NE = "y"
ff-Adlm-NG = "y"
ff-Adlm-SL = "y"
ff-Adlm-SN = "y"
ff-Latn = "y"
ff-Latn-BF = "y"
ff-Latn-CM = "y"
ff-Latn-GH = "y"
ff-Latn-GM = "y"
ff-Latn-GN = "y"
ff-Latn-GW = "y"
ff-Latn-LR = "y"
ff-Latn-MR = "y"
ff-Latn-NE = "y"
ff-Latn-NG = "y"
ff-Latn-SL = "y"
ff-Latn-SN = "y"
fi = "y"
fi-FI = "y"
fil = "y"
fil-PH = "y"
fo = "y"
fo-DK = "y"
fo-FO = "y"
fr = "y"
fr-BE = "y"
fr-BF = "y"
fr-BI = "y"
fr-BJ = "y"
fr-BL = "y"
fr-CA = "y"
fr-CD = "y"
fr-CF = "y"
fr-CG = "y"
fr-CH = "y"
fr-CI = "y"
fr-CM = "y"
fr-DJ = "y"
fr-DZ = "y"
fr-FR = "y"
fr-GA = "y"
fr-GF = "y"
fr-GN = "y"
fr-GP = "y"
fr-GQ = "y"
fr-HT = "y"
fr-KM = "y"
fr-LU = "y"
fr-MA = "y"
fr-MC = "y"
fr-MF = "y"
fr-MG = "y"
fr-ML = "y"
fr-MQ = "y"
fr-MR = "y"
fr-MU = "y"
fr-NC = "y"
fr-NE = "y"
fr-PF = "y"
fr-PM = "y"
fr-RE = "y"
fr-RW = "y"
fr-SC = "y"
fr-SN = "y"
fr-SY = "y"
fr-TD = "y"
fr-TG = "y"
fr-TN = "y"
fr-VU = "y"
fr-WF = "y"
fr-YT = "y"
fur = "y"
fur-IT = "y"
fy = "y"
fy-NL = "y"
ga = "y"
ga-GB = "y"
ga-IE = "y"
gd = "y"
gd-GB = "y"
gl = "y"
gl-ES = "y"
gsw = "y"
gsw-CH = "y"
gsw-FR = "y"
gsw-LI = "y"
gu = "y"
gu-IN = "y"
guz = "y"
guz-KE = "y"
gv = "y"
gv-IM = "y"
ha = "y"
ha-GH = "y"
ha-NE = "y"
ha-NG = "y"
haw = "y"
haw-US = "y"
he = "y"
he-IL = "y"
hi = "y"
hi-IN = "y"
hi-Latn = "y"
hi-Latn-IN = "y"
hr = "y."
hr-BA = "y."
hr-HR = "y."
hsb = "y"
hsb-DE = "y"
hu = "y."
hu-HU = "y."
hy = "y"
hy-AM = "y"
ia = "y"
ia-001 = "y"
id = "y"
id-ID = "y"
ig = "y"
ig-NG = "y"
ii = "y"
ii-CN = "y"
is = "y"
is-IS = "y"
it = "y"
it-CH = "y"
it-IT = "y"
it-SM = "y"
it-VA = "y"
ja = "y年"
ja-JP = "y年"
jgo = "y"
jgo-CM = "y"
jmc = "y"
jmc-TZ = "y"
jv = "y"
jv-ID = "y"
ka = "y"
ka-GE = "y"
kab = "y"
kab-DZ = "y"
kam = "y"
kam-KE = "y"
kde = "y"
kde-TZ = "y"
kea = "y"
kea-CV = "y"
kgp = "y"
kgp-BR = "y"
khq = "y"
khq-ML = "y"
ki = "y"
ki-KE = "y"
kk = "y"
kk-KZ = "y"
kkj = "y"
kkj-CM = "y"
kl = "y"
kl-GL = "y"
kln = "y"
kln-KE = "y"
km = "y"
km-KH = "y"
kn = "y"
kn-IN = "y"
ko = "y년"
ko-KP = "y년"
ko-KR = "y년"
kok = "y"
kok-IN = "y"
ks = "y"
ks-Arab = "y"
ks-Arab-IN = "y"
ks-Deva = "y"
ks-Deva-IN = "y"
ksb = "y"
ksb-TZ = "y"
ksf = "y"
ksf-CM = "y"
ksh = "y"
ksh-DE = "y"
ku = "y"
ku-TR = "y"
kw = "y"
kw-GB = "y"
ky = "y"
ky-KG = "y"
lag = "y"
lag-TZ = "y"
lb = "y"
lb-LU = "y"
lg = "y"
lg-UG = "y"
lkt = "y"
lkt-US = "y"
ln = "y"
ln-AO = "y"
ln-CD = "y"
ln-CF = "y"
ln-CG = "y"
lo = "y"
lo-LA = "y"
lrc = "y"
lrc-IQ = "y"
lrc-IR = "y"
lt = "y"
lt-LT = "y"
lu = "y"
lu-CD = "y"
luo = "y"
luo-KE = "y"
luy = "y"
luy-KE = "y"
lv = "y. 'g'."
lv-LV = "y. 'g'."
mai = "y"
mai-IN = "y"
mas = "y"
mas-KE = "y"
mas-TZ = "y"
mer = "y"
mer-KE = "y"
mfe = "y"
mfe-MU = "y"
mg = "y"
mg-MG = "y"
mgh = "y"
mgh-MZ = "y"
mgo = "y"
mgo-CM = "y"
mi = "y"
mi-NZ = "y"
mk = "y"
mk-MK = "y"
ml = "y"
ml-IN = "y"
mn = "y"
mn-MN = "y"
mni = "y"
mni-Beng = "y"
mni-Beng-IN = "y"
mr = "y"
mr-IN = "y"
ms = "y"
ms-BN = "y"
ms-ID = "y"
ms-MY = "y"
ms-SG = "y"
mt = "y"
mt-MT = "y"
mua = "y"
mua-CM = "y"
my = "y"
my-MM = "y"
mzn = "y"
mzn-IR = "y"
naq = "y"
naq-NA = "y"
nb = "y"
nb-NO = "y"
nb-SJ = "y"
nd = "y"
nd-ZW = "y"
ne = "y"
ne-IN = "y"
ne-NP = "y"
nl = "y"
nl-AW = "y"
nl-BE = "y"
nl-BQ = "y"
nl-CW = "y"
nl-NL = "y"
nl-SR = "y"
nl-SX = "y"
nmg = "y"
nmg-CM = "y"
nn = "y"
nn-NO = "y"
nnh = "y"
nnh-CM = "y"
; The following line has a space before the key because it is a keyword
 no = "y"
nus = "y"
nus-SS = "y"
nyn = "y"
nyn-UG = "y"
om = "y"
om-ET = "y"
om-KE = "y"
or = "y"
or-IN = "y"
os = "y"
os-GE = "y"
os-RU = "y"
pa = "y"
pa-Arab = "y"
pa-Arab-PK = "y"
pa-Guru = "y"
pa-Guru-IN = "y"
pcm = "y"
pcm-NG = "y"
pl = "y"
pl-PL = "y"
ps = "G y"
ps-AF = "G y"
ps-PK = "G y"
pt = "y"
pt-AO = "y"
pt-BR = "y"
pt-CH = "y"
pt-CV = "y"
pt-GQ = "y"
pt-GW = "y"
pt-LU = "y"
pt-MO = "y"
pt-MZ = "y"
pt-PT = "y"
pt-ST = "y"
pt-TL = "y"
qu = "y"
qu-BO = "y"
qu-EC = "y"
qu-PE = "y"
rm = "y"
rm-CH = "y"
rn = "y"
rn-BI = "y"
ro = "y"
ro-MD = "y"
ro-RO = "y"
rof = "y"
rof-TZ = "y"
ru = "y"
ru-BY = "y"
ru-KG = "y"
ru-KZ = "y"
ru-MD = "y"
ru-RU = "y"
ru-UA = "y"
rw = "y"
rw-RW = "y"
rwk = "y"
rwk-TZ = "y"
sa = "y"
sa-IN = "y"
sah = "y"
sah-RU = "y"
saq = "y"
saq-KE = "y"
sat = "y"
sat-Olck = "y"
sat-Olck-IN = "y"
sbp = "y"
sbp-TZ = "y"
sc = "y"
sc-IT = "y"
sd = "y"
sd-Arab = "y"
sd-Arab-PK = "y"
sd-Deva = "y"
sd-Deva-IN = "y"
se = "y"
se-FI = "y"
se-NO = "y"
se-SE = "y"
seh = "y"
seh-MZ = "y"
ses = "y"
ses-ML = "y"
sg = "y"
sg-CF = "y"
shi = "y"
shi-Latn = "y"
shi-Latn-MA = "y"
shi-Tfng = "y"
shi-Tfng-MA = "y"
si = "y"
si-LK = "y"
sk = "y"
sk-SK = "y"
sl = "y"
sl-SI = "y"
smn = "y"
smn-FI = "y"
sn = "y"
sn-ZW = "y"
so = "y"
so-DJ = "y"
so-ET = "y"
so-KE = "y"
so-SO = "y"
sq = "y"
sq-AL = "y"
sq-MK = "y"
sq-XK = "y"
sr = "y."
sr-Cyrl = "y."
sr-Cyrl-BA = "y."
sr-Cyrl-ME = "y."
sr-Cyrl-RS = "y."
sr-Cyrl-XK = "y."
sr-Latn = "y."
sr-Latn-BA = "y."
sr-Latn-ME = "y."
sr-Latn-RS = "y."
sr-Latn-XK = "y."
su = "y"
su-Latn = "y"
su-Latn-ID = "y"
sv = "y"
sv-AX = "y"
sv-FI = "y"
sv-SE = "y"
sw = "y"
sw-CD = "y"
sw-KE = "y"
sw-TZ = "y"
sw-UG = "y"
ta = "y"
ta-IN = "y"
ta-LK = "y"
ta-MY = "y"
ta-SG = "y"
te = "y"
te-IN = "y"
teo = "y"
teo-KE = "y"
teo-UG = "y"
tg = "y"
tg-TJ = "y"
th = "G y"
th-TH = "G y"
ti = "y"
ti-ER = "y"
ti-ET = "y"
tk = "y"
tk-TM = "y"
to = "y"
to-TO = "y"
tr = "y"
tr-CY = "y"
tr-TR = "y"
tt = "y"
tt-RU = "y"
twq = "y"
twq-NE = "y"
tzm = "y"
tzm-MA = "y"
ug = "y"
ug-CN = "y"
uk = "y"
uk-UA = "y"
ur = "y"
ur-IN = "y"
ur-PK = "y"
uz = "y"
uz-Arab = "y"
uz-Arab-AF = "y"
uz-Cyrl = "y"
uz-Cyrl-UZ = "y"
uz-Latn = "y"
uz-Latn-UZ = "y"
vai = "y"
vai-Latn = "y"
vai-Latn-LR = "y"
vai-Vaii = "y"
vai-Vaii-LR = "y"
vi = "y"
vi-VN = "y"
vun = "y"
vun-TZ = "y"
wae = "y"
wae-CH = "y"
wo = "y"
wo-SN = "y"
xh = "y"
xh-ZA = "y"
xog = "y"
xog-UG = "y"
yav = "y"
yav-CM = "y"
yi = "y"
yi-001 = "y"
yo = "y"
yo-BJ = "y"
yo-NG = "y"
yrl = "y"
yrl-BR = "y"
yrl-CO = "y"
yrl-VE = "y"
yue = "y年"
yue-Hans = "y年"
yue-Hans-CN = "y年"
yue-Hant = "y年"
yue-Hant-HK = "y年"
zgh = "y"
zgh-MA = "y"
zh = "y年"
zh-Hans = "y年"
zh-Hans-CN = "y年"
zh-CN = "y年"
zh-Hans-HK = "y年"
zh-Hans-MO = "y年"
zh-Hans-SG = "y年"
zh-Hant = "y年"
zh-Hant-HK = "y年"
zh-Hant-MO = "y年"
zh-Hant-TW = "y年"
zh-TW = "y年"
zu = "y"
zu-ZA = "y"
