# $Id$

# Add some foreign keys

ALTER TABLE %DB_TBL_PREFIX%room
  ADD FOREIGN KEY (area_id) 
    REFERENCES %DB_TBL_PREFIX%area(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE %DB_TBL_PREFIX%repeat
  ADD FOREIGN KEY (room_id) 
    REFERENCES %DB_TBL_PREFIX%room(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
    
ALTER TABLE %DB_TBL_PREFIX%entry
  ADD FOREIGN KEY (room_id) 
    REFERENCES %DB_TBL_PREFIX%room(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
